build_env: &build_env
  working_directory: ~/album-server
  docker:
    - image: circleci/node:12.13.0
version: 2.18
jobs:
  install:
    <<: *build_env
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm ci
  deploy:
    <<: *build_env
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: ssh-deploy
          command: |
            echo ${SSH_KNOWN_HOST} > ~/.ssh/known_hosts
            rm -rf ~/album-server/.git
            scp -r ~/album-server ${SSH_USER}@${SSH_HOST}:~/app
            ssh ${SSH_USER}@${SSH_HOST} "sh ~/run-app.sh"
workflows:
  version: 2
  install_and_deploy:
    jobs:
      - install
      - deploy
