version: 2.18
jobs:
  install:
    working_directory: ~/album-server
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm ci
  deploy:
    working_directory: ~/album-server
    steps:
      - add_ssh_keys
      - run:
          name: ssh-deploy
          command: |
            echo ${SSH_KNOWN_HOST} > ~/.ssh/known_hosts
            ssh ${SSH_USER}@${SSH_HOST}
workflows:
  version: 2
  install_and_deploy:
    jobs:
      - install
      - deploy
